server:
  port: 8090

spring:
  application:
    name: Employee-Organization

  datasource:
    url: jdbc:postgresql://localhost:5432/employeedb
    username: postgres
    password: venkat
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      
   
  security:
    user:
      name: ramana
      password: ramana123
  
